var hide_empty_list=false;
addListGroup("embedded-search1", "manufacturers");
	addList("manufacturers", "Any Manufacturer", "Any", "dummy-manufacturers", "1");
	addList("manufacturers", "Atmel", "191", "Atmel");
	addList("manufacturers", "Cypress Semiconductor", "653", "Cypress Semiconductor");
	addList("manufacturers", "Freescale Semiconductor", "331", "Freescale Semiconductor");
	addList("manufacturers", "Infineon Technologies", "347", "Infineon Technologies");
	addList("manufacturers", "Intel", "6", "Intel");
	addList("manufacturers", "Microchip Technology", "612", "Microchip Technology");
	addList("manufacturers", "NXP Semiconductors", "107", "NXP Semiconductors");
	addList("manufacturers", "Renesas Electronics", "176", "Renesas Electronics");
	addList("manufacturers", "Silicon Laboratories", "622", "Silicon Laboratories");
	addList("manufacturers", "STMicroelectronics", "188", "STMicroelectronics");
	addList("manufacturers", "Texas Instruments", "2", "Texas Instruments");
	addList("manufacturers", "Zilog, Inc.", "641", "Zilog, Inc.");


addListGroup("embedded-search2a", "instructions");
	addList("instructions", "Any Instructions", "Any", "dummy-instructions", "1");
	addList("instructions", "8051", "18", "");
	addList("instructions", "ARM", "10", "");
	addList("instructions", "AVR", "19", "");
	addList("instructions", "C2000™", "56", "");
	addList("instructions", "C6000™ DSP", "67", "");
	addList("instructions", "Freescale 56800DSC", "32", "");
	addList("instructions", "Freescale ColdFire", "14", "");
	addList("instructions", "Freescale HC(S)08", "16", "");
	addList("instructions", "Infineon C166®", "35", "");
	addList("instructions", "Microchip PIC®", "30", "");
	addList("instructions", "MIPS", "36", "");
	addList("instructions", "MSP430", "27", "");
	addList("instructions", "PowerPC", "28", "");
	addList("instructions", "Renesas 740", "63", "");
	addList("instructions", "Renesas 78K0R", "74", "");
	addList("instructions", "Renesas H8", "11", "");
	addList("instructions", "Renesas M16C", "12", "");
	addList("instructions", "Renesas RX", "65", "");
	addList("instructions", "Renesas SuperH", "13", "");
	addList("instructions", "Renesas V850", "73", "");
	addList("instructions", "STM8", "61", "");
	addList("instructions", "STMicroelectronics ST7", "22", "");
	addList("instructions", "TriCore®", "51", "");
	addList("instructions", "x86", "31", "");
	addList("instructions", "XC800", "60", "");
	addList("instructions", "Zilog Z80®", "59", "");
	addList("instructions", "Zilog Z8® CPU", "57", "");
	addList("instructions", "ZNEO CPU", "58", "");
addListGroup("embedded-search2b", "instructions");
	addList("instructions", "Any Instruction Set", "Any", "dummy-instructions", "1");
	addList("instructions", "STMicroelectronics ST7", "22", "");
	addList("instructions", "AVR", "19", "");
	addList("instructions", "8051", "18", "");
	addList("instructions", "Freescale 56800DSC", "32", "");
	addList("instructions", "Freescale ColdFire", "14", "");
	addList("instructions", "Freescale HC(S)08", "16", "");
	addList("instructions", "Renesas H8", "11", "");
	addList("instructions", "Renesas M16C", "12", "");
addListGroup("embedded-search2c", "instructions");
	addList("instructions", "Any Instruction Set", "Any", "dummy-instructions", "1");
	addList("instructions", "x86", "31", "");
	addList("instructions", "AVR", "19", "");
	addList("instructions", "ARM", "10", "");
	addList("instructions", "Freescale ColdFire", "14", "");
	addList("instructions", "ADI Blackfin", "33", "");
	addList("instructions", "PowerPC", "28", "");
	addList("instructions", "Renesas H8", "11", "");
	addList("instructions", "Renesas SuperH", "13", "");
	addList("instructions", "XScale", "4", "");


addListGroup("embedded-search3", "cores");
	addList("cores", "Any Core Architecture", "Any", "dummy-cores","1");
	addList("cores", "8051", "18", "");
	addList("cores", "ARM", "10", "");
	addList("cores", "AVR", "19", "");
	addList("cores", "C2000™", "56", "");
	addList("cores", "C6000™ DSP", "67", "");
	addList("cores", "Freescale 56800DSC", "32", "");
	addList("cores", "Freescale ColdFire", "14", "");
	addList("cores", "Freescale HC(S)08", "16", "");
	addList("cores", "Infineon C166®", "35", "");
	addList("cores", "Microchip PIC®", "30", "");
	addList("cores", "MIPS", "36", "");
	addList("cores", "MSP430", "27", "");
	addList("cores", "PowerPC", "28", "");
	addList("cores", "Renesas 740", "63", "");
	addList("cores", "Renesas 78K0R", "74", "");
	addList("cores", "Renesas H8", "11", "");
	addList("cores", "Renesas M16C", "12", "");
	addList("cores", "Renesas RX", "65", "");
	addList("cores", "Renesas SuperH", "13", "");
	addList("cores", "Renesas V850", "73", "");
	addList("cores", "STM8", "61", "");
	addList("cores", "STMicroelectronics ST7", "22", "");
	addList("cores", "TriCore®", "51", "");
	addList("cores", "x86", "31", "");
	addList("cores", "XC800", "60", "");
	addList("cores", "Zilog Z80®", "59", "");
	addList("cores", "Zilog Z8® CPU", "57", "");
	addList("cores", "ZNEO CPU", "58", "");


addListGroup("embedded-search4", "families");
	addList("families", "Any Part Family", "Any", "dummy-families", "1");
	addList("families", "38000/740 Series", "363", "");
	addList("families", "56F8XXX", "236", "");
	addList("families", "78K0R", "389", "");
	addList("families", "78K0S", "364", "");
	addList("families", "AP7000", "190", "");
	addList("families", "AT32UC3L", "333", "");
	addList("families", "AT90USB", "210", "");
	addList("families", "AT91CAP7S", "347", "");
	addList("families", "AT91SAM3N", "397", "");
	addList("families", "AT91SAM3S", "355", "");
	addList("families", "AT91SAM3U", "339", "");
	addList("families", "AT91SAM7", "2", "");
	addList("families", "AT91SAM9", "3", "");
	addList("families", "Atom™ Processor 200 series", "321", "");
	addList("families", "Atom™ Processor 300 Series", "322", "");
	addList("families", "Atom™ Processor Z5XX Series", "318", "");
	addList("families", "ATtinyAVR", "209", "");
	addList("families", "Auto AVR", "203", "");
	addList("families", "Automotive and Industrial Microcontrollers", "415", "");
	addList("families", "AVR picoPower", "254", "");
	addList("families", "AVR32 UC3", "252", "");
	addList("families", "AVR® XMEGA", "351", "");
	addList("families", "C166®", "303", "");
	addList("families", "C505CA", "301", "");
	addList("families", "C515C", "300", "");
	addList("families", "C6-Integra™ DSP+ARM®", "403", "");
	addList("families", "CAN AVR", "204", "");
	addList("families", "ColdFire V1", "332", "");
	addList("families", "DaVinci™", "264", "");
	addList("families", "DLPC100", "395", "");
	addList("families", "dsPIC30F DSC", "298", "");
	addList("families", "dsPIC33F DSC", "299", "");
	addList("families", "Flexis AC", "294", "");
	addList("families", "Flexis JM", "278", "");
	addList("families", "Flexis™ QE", "256", "");
	addList("families", "H8/300H SLP", "141", "");
	addList("families", "H8/300L SLP", "140", "");
	addList("families", "H8/3062BL", "148", "");
	addList("families", "H8/Tiny", "142", "");
	addList("families", "H8S/2100", "143", "");
	addList("families", "H8S/2200", "144", "");
	addList("families", "H8S/2300", "145", "");
	addList("families", "H8S/2317BL", "149", "");
	addList("families", "H8S/2400", "289", "");
	addList("families", "H8S/2600", "146", "");
	addList("families", "H8SX/1500", "232", "");
	addList("families", "H8SX/1600", "147", "");
	addList("families", "HCS08AS", "171", "");
	addList("families", "HCS08GP", "168", "");
	addList("families", "HCS08L", "313", "");
	addList("families", "High-Performance, Analog-Intensive MCUs", "414", "");
	addList("families", "i.MX", "342", "");
	addList("families", "LCD AVR", "205", "");
	addList("families", "Lighting AVR", "206", "");
	addList("families", "LPC1000", "311", "");
	addList("families", "LPC11Cxx", "360", "");
	addList("families", "LPC11xx", "361", "");
	addList("families", "LPC2000", "1", "");
	addList("families", "LPC3000", "17", "");
	addList("families", "LPC4000", "393", "");
	addList("families", "LPC900", "189", "");
	addList("families", "M16C/60", "152", "");
	addList("families", "M16C/Tiny", "151", "");
	addList("families", "M32C/80", "154", "");
	addList("families", "MCF52X", "165", "");
	addList("families", "MCF53X", "166", "");
	addList("families", "MCF54X", "167", "");
	addList("families", "Mega AVR", "207", "");
	addList("families", "MSP430", "297", "");
	addList("families", "OMAP35X", "317", "");
	addList("families", "PIC10F200", "308", "");
	addList("families", "PIC10F220", "309", "");
	addList("families", "PIC12F", "310", "");
	addList("families", "PIC16", "306", "");
	addList("families", "PIC18", "307", "");
	addList("families", "PIC24F MCU", "295", "");
	addList("families", "PIC24H MCU", "296", "");
	addList("families", "PIC32", "286", "");
	addList("families", "PowerQUICC I (8xx)", "392", "");
	addList("families", "PowerQUICC II (82xx)", "391", "");
	addList("families", "PowerQUICC II Pro (MPC83xx)", "246", "");
	addList("families", "PowerQUICC III (85xx)", "285", "");
	addList("families", "PSoC® 3", "366", "");
	addList("families", "PSoC® 5", "367", "");
	addList("families", "QorIQ", "330", "");
	addList("families", "R8C/Tiny", "150", "");
	addList("families", "Renesas RX 600", "368", "");
	addList("families", "RL78", "405", "");
	addList("families", "RS08", "169", "");
	addList("families", "S08D", "270", "");
	addList("families", "SH-Ether", "157", "");
	addList("families", "SH-Tiny", "233", "");
	addList("families", "SH2A", "291", "");
	addList("families", "SH7010", "238", "");
	addList("families", "SH7040", "239", "");
	addList("families", "SH7046", "240", "");
	addList("families", "SH7047", "155", "");
	addList("families", "SH7080", "241", "");
	addList("families", "SH7144", "156", "");
	addList("families", "SH7146", "242", "");
	addList("families", "SH7149", "290", "");
	addList("families", "SH7210", "245", "");
	addList("families", "SH7606", "243", "");
	addList("families", "Silicon Labs QuickSense™ MCUs", "413", "");
	addList("families", "Sitara™ ARM® MPU", "404", "");
	addList("families", "Small Form Factor MCUs", "281", "");
	addList("families", "Smart Battery AVR", "208", "");
	addList("families", "ST7226x", "177", "");
	addList("families", "ST7232x", "178", "");
	addList("families", "ST7236x", "179", "");
	addList("families", "ST7Lite", "176", "");
	addList("families", "ST7MC", "180", "");
	addList("families", "Stellaris®", "362", "");
	addList("families", "STM32", "257", "");
	addList("families", "STM8L", "350", "");
	addList("families", "STM8S", "349", "");
	addList("families", "STn8800", "16", "");
	addList("families", "STR7", "7", "");
	addList("families", "STR9", "20", "");
	addList("families", "TC1130", "305", "");
	addList("families", "TC116x", "304", "");
	addList("families", "TMS320C2000™ Real-time control MCUs", "323", "");
	addList("families", "Ultra Low-Power Microcontrollers", "283", "");
	addList("families", "USB Microcontrollers", "279", "");
	addList("families", "V850ES", "390", "");
	addList("families", "Wireless MCUs", "412", "");
	addList("families", "XC166", "302", "");
	addList("families", "XC86x Series", "346", "");
	addList("families", "XC87x Series", "345", "");
	addList("families", "XC88x Series", "344", "");
	addList("families", "XE166", "272", "");
	addList("families", "Z8", "337", "");
	addList("families", "Z8 Encore!", "329", "");
	addList("families", "Z8 Encore! MC", "328", "");
	addList("families", "Z8 Encore! XP", "326", "");
	addList("families", "Z80", "338", "");
	addList("families", "ZNEO Z16F", "334", "");


addListGroup("embedded-search5", "types");
	addList("types", "Any Tool Type", "Any", "dummy-types", "1");
	addList("types", "Development Kits etc.", "4", "");
	addList("types", "IDEs (Compilers etc.)", "9", "");
	addList("types", "Daughter/OEM Boards", "7", "");
	addList("types", "Debuggers / Simulators", "10", "");
	addList("types", "Emulators", "2", "");
	addList("types", "JTAG Probes", "5", "");
	addList("types", "Operating Systems", "12", "");
	addList("types", "Stacks/Protocols/File systems", "13", "");
	addList("types", "Reference Designs", "3", "");
	addList("types", "Wireless Modules", "15", "");
	addList("types", "Other Software Tools", "11", "");
	addList("types", "Software Design", "8", "");
	addList("types", "Programmers", "6", "");
	addList("types", "Accessories", "1", "");


addListGroup("embedded-search6", "companies");
	addList("companies", "Any Tool Provider", "Any", "dummy-companies", "1");
	addList("types", "Abatron AG", "30", "");
	addList("types", "Arium", "36", "");
	addList("types", "ARM", "34", "");
	addList("types", "Atmel", "191", "");
	addList("types", "Atollic Inc.", "678", "");
	addList("types", "Blackhawk", "639", "");
	addList("types", "Bluetechnix GmbH", "652", "");
	addList("types", "CCS", "654", "");
	addList("types", "Circuitco", "665", "");
	addList("types", "CMX Systems", "35", "");
	addList("types", "CodeSourcery", "617", "");
	addList("types", "Cogent Computer Systems", "637", "");
	addList("types", "connectBlue", "666", "");
	addList("types", "Critical Link", "673", "");
	addList("types", "Cypress Semiconductor", "653", "");
	addList("types", "Digi", "669", "");
	addList("types", "dresden elektronik", "659", "");
	addList("types", "Embedded Artists AB", "621", "");
	addList("types", "Ember", "676", "");
	addList("types", "Equinox", "658", "");
	addList("types", "Freescale Semiconductor", "331", "");
	addList("types", "Future Designs, Inc.", "647", "");
	addList("types", "HCC-Embedded", "643", "");
	addList("types", "Hitex Development Tools", "142", "");
	addList("types", "IAR Systems", "106", "");
	addList("types", "Infineon Technologies", "347", "");
	addList("types", "Intel", "6", "");
	addList("types", "Interniche Technologies", "642", "");
	addList("types", "iSYSTEM", "218", "");
	addList("types", "Keil", "163", "");
	addList("types", "Laird Tech", "672", "");
	addList("types", "Linx Technologies", "668", "");
	addList("types", "Logic", "633", "");
	addList("types", "Macraigor Systems", "323", "");
	addList("types", "Micrium", "634", "");
	addList("types", "Micro Digital Inc.", "613", "");
	addList("types", "Micro/sys, Inc.", "649", "");
	addList("types", "Microchip Technology", "612", "");
	addList("types", "microEngineering Labs", "660", "");
	addList("types", "MIPS Technologies, Inc.", "640", "");
	addList("types", "Multi-Tech Systems", "667", "");
	addList("types", "NetBurner, Inc", "655", "");
	addList("types", "NXP Semiconductors", "107", "");
	addList("types", "Phyton", "657", "");
	addList("types", "Raisonance SAS", "615", "");
	addList("types", "Renesas Electronics", "176", "");
	addList("types", "RFM", "664", "");
	addList("types", "Ronetix", "645", "");
	addList("types", "Sage Electronic Engineering, LLC.", "677", "");
	addList("types", "SEGGER Microcontroller", "230", "");
	addList("types", "Signum Systems Corp", "243", "");
	addList("types", "Silicon Laboratories", "622", "");
	addList("types", "STMicroelectronics", "188", "");
	addList("types", "Synopsys, Inc.", "632", "");
	addList("types", "Tag-Connect", "674", "");
	addList("types", "Texas Instruments", "2", "");
	addList("types", "Ultimate Solutions, Inc.", "638", "");
	addList("types", "Xeltek", "656", "");
	addList("types", "Zilog, Inc.", "641", "");


addListGroup("embedded-search7a", "frequency7a");
	addList("frequency7a", "Any Frequency", "Any", "dummy-frequency", "1");
	addList("frequency7a", "> 10 MHz", "10MHz", "");
	addList("frequency7a", "> 25 MHz", "25MHz", "");
	addList("frequency7a", "> 50 MHz", "50MHz", "");
	addList("frequency7a", "> 100 MHz", "100MHz", "");
	addList("frequency7a", "> 200 MHz", "200MHz", "");
	addList("frequency7a", "> 300 MHz", "300MHz", "");


addListGroup("embedded-search7b", "frequency7b");
	addList("frequency7b", "Any Frequency", "Any", "dummy-frequency", "1");
	addList("frequency7b", "> 10 MHz", "10MHz", "");
	addList("frequency7b", "> 25 MHz", "25MHz", "");
	addList("frequency7b", "> 50 MHz", "50MHz", "");


addListGroup("embedded-search8a", "flashrom");
	addList("flashrom", "Any Flash/ROM", "Any", "dummy-flashrom", "1");
	addList("flashrom", "0", "0", "");
	addList("flashrom", "ROM", "ROM", "");
	addList("flashrom", "0K to 4K", "0Kbytes to 4Kbytes", "");
	addList("flashrom", "4K to 8K", "4Kbytes to 8Kbytes", "");
	addList("flashrom", "8K to 16K", "8Kbytes to 16Kbytes", "");
	addList("flashrom", "16K to 32K", "16Kbytes to 32Kbytes", "");
	addList("flashrom", "32K to 64K", "32Kbytes to 64Kbytes", "");
	addList("flashrom", "> 64K", "=64Kbytes", "");
	addList("flashrom", "> 256K", "=256Kbytes", "");


addListGroup("embedded-search8b", "flashrom");
	addList("flashrom", "Any Flash/ROM", "Any", "dummy-flashrom", "1");
	addList("flashrom", "0", "0", "");
	addList("flashrom", "ROM", "ROM", "");
	addList("flashrom", "0K to 4K", "0Kbytes to 4Kbytes", "");
	addList("flashrom", "4K to 8K", "4Kbytes to 8Kbytes", "");
	addList("flashrom", "8K to 16K", "8Kbytes to 16Kbytes", "");
	addList("flashrom", "16K to 32K", "16Kbytes to 32Kbytes", "");
	addList("flashrom", "32K to 64K", "32Kbytes to 64Kbytes", "");
	addList("flashrom", "> 64K", "=64Kbytes", "");


addListGroup("embedded-search8c", "flashrom");
	addList("flashrom", "Any Flash/ROM", "Any", "dummy-flashrom", "1");
	addList("flashrom", "0", "0", "");
	addList("flashrom", "ROM", "ROM", "");
	addList("flashrom", "< 64K", "<64Kbytes", "");
	addList("flashrom", "> 64K", "=64Kbytes", "");
	addList("flashrom", "> 256K", "=256Kbytes", "");


addListGroup("embedded-search9", "pincount");
	addList("pincount", "Any Pin Count", "Any", "dummy-pincount", "1");
	addList("pincount", "< 8", "8", "");
	addList("pincount", "< 16", "16", "");
	addList("pincount", "< 24", "24", "");
	addList("pincount", "< 40", "40", "");
	addList("pincount", "< 60", "60", "");
	addList("pincount", "< 100", "100", "");


addListGroup("embedded-search10", "core_features");
	addList("core_features", "Any Core Feature", "Any", "dummy-core_features", "1");
	addList("core_features", "FPU", "FPU", "");
	addList("core_features", "MAC", "MAC", "");
	addList("core_features", "MMU", "MMU", "");
	addList("core_features", "Super Scalar", "Super Scalar", "");
	addList("core_features", "DSP Instructions", "DSP Instructions", "");


addListGroup("embedded-search11", "mips");
	addList("mips", "Any MIPS (Dhrystone)", "Any", "dummy-mips", "1");
	addList("mips", "< 100", "<100", "");
	addList("mips", "> 100", ">100", "");
	addList("mips", "> 200", ">200", "");
	addList("mips", "> 300", ">300", "");
